### ISSUE TITLE
Sources.

### ISSUE THREAD

**Issue by northdakota** [ZencashOfficial/Sphere_by_Horizen#1]
Where is source code?

**Comment by elkimek** [comment]
Not opensource according to Code Particle dev :(

**Comment by vherus** [comment]
Open-sourcing Sphere is most certainly planned. Though I can't give any dates, you should expect it to happen following the release of sidechains. This should allow us to get the app out of beta status, and will provide a way for developers to see how sidechains can be utilised in the applications they develop.

**Comment by ArnaudKleinveld** [comment]
Is this real or fake? Now Mar 1, 2020 and still no sources..

**Comment by asbachb** [comment]
This wallet is recommended as wallet replacement for swing wallet but no sources are available to check what it is doing nor a statement why it's closed source at all.

**Comment by PowerVANO** [comment]
@asbachb We have plans for open sourcing it. Zendoo has been the focus for the team though and Sphere by Horizen has to wait a bit more.
But the plans to open-source it are there.

**Comment by asbachb** [comment]
Actually I don't understand what's the problem of releasing the sources when it's planned anyway? Horizen is and was heavily based on OSS. But is not willing to share their own one since more than three years.

Are you afraid of feedback? Actually I don't see the problem. 

I assume you work with git anyway:
`git remote add github https://github.com/HorizenOfficial/Sphere_by_Horizen.git`
`git push github master`

Don't need much of a planning phase of several month.
