### ISSUE TITLE
Unable to import Arizen wallet

### ISSUE THREAD

**Issue by lookfirst** [ZencashOfficial/Sphere_by_Horizen#23]
There should be a mechanism to import an arizen wallet.

**Comment by uanl979** [comment]
Hi @lookfirst 

Since Sphere is deterministic, meaning that the private keys are generated from a seed. It is not possible to import private keys not generated from a starting point (a seed). The closest feature that could help you move your balances to sphere is to sweep balances and move them to addresses inside Sphere. You can find this option under tools in the menu bar.

I imagine you have stake addresses for nodes in Arizen, please take a look at this article on how to change stake addresses.

https://horizenofficial.atlassian.net/wiki/spaces/ZEN/pages/136872049/Change+Staking+Address

If you think you need further assistance, could you raise a ticket on our [support system ](https://horizenofficial.atlassian.net/servicedesk/customer/portals)

Regards :)
