### ISSUE TITLE
Transaction History is an empty

### ISSUE THREAD

**Issue by VadimMalykhin** [ZencashOfficial/Sphere_by_Horizen#3]
Transaction History is an empty in my last created wallet and transaction a few hours ago in light and full mode. But looks like i can use my funds  ([Transaction ID](https://explorer.zensystem.io/tx/0a865bb4291663e9dd35e1e6404be973e1e523928c57767628f59cb82a20c565))

![Screenshot](https://user-images.githubusercontent.com/158365/50864688-e1cea200-13b3-11e9-8f93-4c66614b31b0.png)

```
OC: Windows 10 v1803
```

**Comment by vherus** [comment]
Hi @VadimMalykhin 

Please accept my sincere apologies for the lack of activity on this report. Though not an excuse, we were still figuring a few logistics out at the time of the first version release. Thank you for your patience.

Version 1.1.0-beta introduced significant improvements to transaction data handling, if you haven't already done so then I recommend upgrading via this link: https://github.com/ZencashOfficial/Sphere_by_Horizen/releases/tag/desktop-v1.1.0-beta

Due to the significant changes in data handling you will need to create a new account and restore your wallet seeds to experience the full effects. In future versions there will be an upgrade mechanism to remove this requirement on the user.
