### ISSUE TITLE
Missing secure node payment transaction

### ISSUE THREAD

**Issue by jasonpulaski** [ZencashOfficial/Sphere_by_Horizen#4]
Secure node payment has not shown up days later.  Others have noted similiar situation in discord channel.

Address with 4 payments 
https://explorer.zensystem.io/address/znoX77jyqgqT7vhaQcK9K19Eq9HvSoXxowB

![capture](https://user-images.githubusercontent.com/35674327/51652433-985a8700-1f5d-11e9-81d1-a5a8537c6fde.PNG)

**Comment by vherus** [comment]
Hi @jasonpulaski 

Please accept my sincere apologies for the lack of activity on this report. Though not an excuse, we were still figuring a few logistics out at the time of the first version release. Thank you for your patience.

Version 1.1.0-beta introduced significant improvements to transaction data handling, if you haven't already done so then I recommend upgrading via this link: https://github.com/ZencashOfficial/Sphere_by_Horizen/releases/tag/desktop-v1.1.0-beta

Due to the significant changes in data handling you will need to create a new account and restore your wallet seeds to experience the full effects. In future versions there will be an upgrade mechanism to remove this requirement on the user.
